#!/usr/bin/env python3
"""
gen_assets.py - embed the homebrew UI assets into a C header for the payload.

Reads:
  homebrew/index.html
  homebrew/catalog.json
  homebrew/logo.jpg
Writes:
  assets.h   (index_html[], catalog_json[], logo_jpg[] byte arrays + lengths)

Run from the native/ dir:
    python tools/gen_assets.py
"""
from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
HOMEBREW = HERE / "homebrew"
OUT = HERE / "assets.h"


def _carray(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x},")
        if len(row) == 16:
            lines.append("  " + "".join(row))
            row = []
    if row:
        lines.append("  " + "".join(row))
    lines.append("};")
    lines.append(f"static const unsigned long {name}_len = {len(data)}UL;")
    return "\n".join(lines)


def main():
    index = (HOMEBREW / "index.html").read_bytes()
    catalog = (HOMEBREW / "catalog.json").read_bytes()
    logo_path = HOMEBREW / "logo.jpg"
    logo = logo_path.read_bytes() if logo_path.exists() else b""

    out = [
        "/* AUTO-GENERATED by tools/gen_assets.py - do not edit. */",
        "#ifndef XENO_ASSETS_H",
        "#define XENO_ASSETS_H",
        "",
        _carray("index_html", index),
        "",
        _carray("catalog_json", catalog),
        "",
        _carray("logo_jpg", logo),
        "",
        "#endif",
        "",
    ]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT}  (index={len(index)}B, catalog={len(catalog)}B, logo={len(logo)}B)")


if __name__ == "__main__":
    main()
