#!/usr/bin/env python3
"""Embed the built React UI (client/dist) into a C source file so the
PS5 web-server ELF (xeno-web.elf) can serve the whole UI from a single
binary — no extra files to copy to the console.

Each file under dist/ is gzipped and emitted as a C byte array plus a
table entry {url_path, content_type, gz_bytes, gz_len, raw_len}. The
server sends them with `Content-Encoding: gzip`, so the browser
inflates them and the ELF stays small.

Usage:  gen_web_assets.py <dist_dir> <out_c> <out_h>
"""
import sys
import os
import gzip

CTYPES = {
    ".html": "text/html; charset=utf-8",
    ".js":   "application/javascript; charset=utf-8",
    ".mjs":  "application/javascript; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg":  "image/svg+xml",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif":  "image/gif",
    ".webp": "image/webp",
    ".ico":  "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf":  "font/ttf",
    ".map":  "application/json; charset=utf-8",
    ".txt":  "text/plain; charset=utf-8",
    ".md":   "text/markdown; charset=utf-8",
    ".wasm": "application/wasm",
    ".wav":  "audio/wav",
    ".mp3":  "audio/mpeg",
    ".ogg":  "audio/ogg",
}


def ctype_for(path: str) -> str:
    _, ext = os.path.splitext(path)
    return CTYPES.get(ext.lower(), "application/octet-stream")


def c_array(name: str, data: bytes) -> str:
    out = [f"static const unsigned char {name}[] = {{"]
    line = "  "
    for i, b in enumerate(data):
        line += f"{b},"
        if len(line) >= 100:
            out.append(line)
            line = "  "
    if line.strip():
        out.append(line)
    out.append("};")
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    dist, out_c, out_h = sys.argv[1], sys.argv[2], sys.argv[3]
    if not os.path.isdir(dist):
        sys.stderr.write(f"dist dir not found: {dist}\n")
        return 1

    entries = []  # (url_path, ctype, var, gz_len, raw_len)
    blobs = []
    idx = 0
    total_gz = 0
    for root, _, files in os.walk(dist):
        for fn in sorted(files):
            fp = os.path.join(root, fn)
            url = "/" + os.path.relpath(fp, dist).replace(os.sep, "/")
            raw = open(fp, "rb").read()
            gz = gzip.compress(raw, 9)
            var = f"asset_{idx}"
            blobs.append(c_array(var, gz))
            entries.append((url, ctype_for(url), var, len(gz), len(raw)))
            total_gz += len(gz)
            idx += 1

    with open(out_c, "w", newline="\n") as f:
        f.write('/* GENERATED by payload/web/gen_web_assets.py — do not edit. */\n')
        f.write('#include "web_assets.h"\n\n')
        for b in blobs:
            f.write(b + "\n\n")
        f.write("const web_asset_t WEB_ASSETS[] = {\n")
        for url, ct, var, gzl, rawl in entries:
            f.write(f'  {{ "{url}", "{ct}", {var}, {gzl}u, {rawl}u }},\n')
        f.write("};\n")
        f.write(f"const int WEB_ASSETS_COUNT = {len(entries)};\n")

    with open(out_h, "w", newline="\n") as f:
        f.write("/* GENERATED by payload/web/gen_web_assets.py — do not edit. */\n")
        f.write("#ifndef WEB_ASSETS_H\n#define WEB_ASSETS_H\n\n")
        f.write("typedef struct {\n")
        f.write("  const char *path;        /* URL path, e.g. \"/index.html\" */\n")
        f.write("  const char *ctype;       /* Content-Type header value */\n")
        f.write("  const unsigned char *gz; /* gzip-compressed bytes */\n")
        f.write("  unsigned int gz_len;     /* compressed length */\n")
        f.write("  unsigned int raw_len;    /* original length */\n")
        f.write("} web_asset_t;\n\n")
        f.write("extern const web_asset_t WEB_ASSETS[];\n")
        f.write("extern const int WEB_ASSETS_COUNT;\n\n")
        f.write("#endif /* WEB_ASSETS_H */\n")

    print(f"embedded {len(entries)} files, {total_gz} gz bytes -> {out_c}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
